# CrewAI Configuration File

# Default settings for all crews
default_settings:
  verbose: 2
  memory: true
  cache: true
  embedder:
    provider: openai
    config:
      model: text-embedding-3-small

# Model configurations
models:
  default:
    model: gpt-4o-mini
    temperature: 0.7
  reasoning:
    model: gpt-4o
    temperature: 0.3
  creative:
    model: gpt-4o
    temperature: 0.9

# Logging configuration
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "/home/foomanchu8008/dotfiles/logs/crewai.log"

# Memory settings
memory:
  provider: chroma
  config:
    chroma_server_host: localhost
    chroma_server_http_port: 8000

# Tools configuration
tools:
  file_reader:
    enabled: true
  code_analyzer:
    enabled: true
  system_monitor:
    enabled: true
  documentation_generator:
    enabled: true
  deployment_checker:
    enabled: true

# Crew configurations
crews:
  code_review:
    description: "Reviews code files for quality, best practices, and potential issues"
    agents:
      - code_reviewer
      - security_analyst
      - performance_optimizer
  project_analysis:
    description: "Reviews projects as a whole for architecture, design, and big picture issues"
    agents:
      - architect
      - design_reviewer
      - scalability_expert
  deployment_troubleshooter:
    description: "Reviews, configures, and troubleshoots deployment issues"
    agents:
      - deployment_engineer
      - infrastructure_specialist
      - security_auditor
  system_troubleshooter:
    description: "Reviews system logs, processes, CPU usage, I/O issues, network anomalies, etc."
    agents:
      - system_analyst
      - performance_engineer
      - network_specialist